"""
author: @guu8hc
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Generated by guu8hc
# Generated time: 2025-04-12 10:15:10.187054
ESP_19 = {
    'Length': 8,
    'ID': 25,
}
LWI_01 = {
    'Length': 8,
    'ID': 16,
}
TSK_07 = {
    'Length': 8,
    'ID': 7,
}
MSG_EMG_01 = {
    'Length': 8,
    'ID': 16,
}
ESP_21 = {
    'Length': 8,
    'ID': 33,
}
MUX_09 = {
    'Length': 8,
    'ID': 9,
}
